### ISSUE TITLE
Додати перевірку по статусу модерації на головній

### ISSUE THREAD

**Issue by katansky** [zmej-gorunuch/dev.renta#1]
Пофіксити вивід топ-оголошень, бо всі ств. оголошення кидає в топ!
Зробити перевірку!

**Comment by zmej-gorunuch** [comment]
на головній має бути топ чи нові оголошення?

**Comment by katansky** [comment]
нові та топ, потім тільки ті шо в топі!

**Comment by zmej-gorunuch** [comment]
ок, там зараз нові виводить, треба тільки додати перевірку по статусу модерації
