### ISSUE TITLE
Квадратні кути при ховері

### ISSUE THREAD

**Issue by klovackdesign** [zmej-gorunuch/dev.renta#10]
Отут при ховері робить квадратні кути блоку, здалось би якби так не було:

![image](https://user-images.githubusercontent.com/31410258/34949548-1530f9a0-fa19-11e7-87d5-536db9e5fcd6.png)

**Comment by katansky** [comment]
якшо піляти з круглими кутами то тільки так вийде!
![image](https://user-images.githubusercontent.com/23053495/35048307-4c2b8c08-fba5-11e7-90fb-91d2550c96dc.png)

**Comment by klovackdesign** [comment]
я бачив багато випадків, де це працює нормально, так шо хз....
Ну хрен з ним, нехай поки буде так, як в тебе на скріні

**Comment by katansky** [comment]
**.jq-selectbox li{
border-radius: 4px;
}**

jquery.formstyler.css - 352 строка коду!
