### ISSUE TITLE
Зробити візитку

### ISSUE THREAD

**Issue by zmej-gorunuch** [zmej-gorunuch/dev.renta#102]
Надрукувати трохи візиток, щоб можна було роздавати, бажано з qr кодом

**Comment by katansky** [comment]
навіть не бажано, а маст хев!

**Comment by klovackdesign** [comment]
Ок, зробимо... А де плануєте роздавати?
Я можу в iJobs в магазі поставити 50-100 шт може розідйуться

**Comment by katansky** [comment]
та просто десь знайомим при зустрічі)

**Comment by klovackdesign** [comment]
Дайте якісь мислі...шо би ви хтіли на візитці бачити?

**Comment by zmej-gorunuch** [comment]
мені подобається як в фб картинка

**Comment by klovackdesign** [comment]
Номера, пошту....ніц такого не ставимо на неї?

**Comment by zmej-gorunuch** [comment]
ставимо все)) номер Славіка

**Comment by katansky** [comment]
номер не треба, тільки сайт і пошта, мб фб

**Comment by klovackdesign** [comment]
є
