### ISSUE TITLE
Модернізація адмінки

### ISSUE THREAD

**Issue by zmej-gorunuch** [zmej-gorunuch/dev.renta#106]
![default](https://user-images.githubusercontent.com/17927037/41538928-15d9dc76-7315-11e8-9be9-e99a5cf618a4.png)
Додав кількість оголошень та зареєстрованих користувачів за день

**Comment by katansky** [comment]
чи можна зробити години додавання оголошення, було б добре, якшо не, то закривай топік!
![image](https://user-images.githubusercontent.com/23053495/41648315-33c6cd8a-7481-11e8-89e5-2ece82f73d7d.png)
