### ISSUE TITLE
Функціонал з неактивними оголошеннями

### ISSUE THREAD

**Issue by katansky** [zmej-gorunuch/dev.renta#107]
Зробити функціонал з неактивними оголошеннями:
1) Після 14 днів (2 тижнів) оголошення стає неактивним;
2) Якшо людина не поновляє його воно автоматично видаляється з бази.

**Comment by zmej-gorunuch** [comment]
1. оголошення активні 1 місяць
2. за 3 дні відправляється лист про деактивацію
3. після 10 днів з дня деактивації, якщо повторно оголошення не активується, воно видаляється
