### ISSUE TITLE
Пропозиція щодо "останніх оголошень" на головній

### ISSUE THREAD

**Issue by klovackdesign** [zmej-gorunuch/dev.renta#111]
Пропоную додати в блоки з оголошеннями назву, або хочаб рубрику...

Якщо рубрику, то в плашку просто "Продаж землі" чи "Оренда квартири" буде. Якщо назву, то просто над/під ціною. Бо не завжди ясно по фотці, що це за оголошення. Що скажете?

**Comment by zmej-gorunuch** [comment]
підтримую, бо сам не раз не міг зрозуміти

**Comment by katansky** [comment]
в понеділок розберемся, думаю перший варіант найкращий!

**Comment by klovackdesign** [comment]
Ну я теж за 1 варіант. Тільки плашки треба буде якось зробити резиновими, щоб під назви категорій по ширині підганяло...

**Comment by klovackdesign** [comment]
![image](https://user-images.githubusercontent.com/31410258/42818218-f2a42dd0-89d8-11e8-9286-3b16f264d4aa.png)
