### ISSUE TITLE
На сторінці з оголошенням не відображає район (мобайл)

### ISSUE THREAD

**Issue by klovackdesign** [zmej-gorunuch/dev.renta#114]
Чомусь не відображає район на сторінці з оголошенням, на моб версії.
Наприклад оце оголошення: https://renta.if.ua/ua/449/dvorivneva-kvartyra-v-centri-pochatok-vul-vovchynecka

Десктоп:
![image](https://user-images.githubusercontent.com/31410258/42290217-928a9c06-7fcc-11e8-9fc0-6ced6ddeb6a6.png)

Мобайл:
![image](https://user-images.githubusercontent.com/31410258/42290212-88715eda-7fcc-11e8-9dcf-c3fa03b603ac.png)

**Comment by katansky** [comment]
виправив!
