### ISSUE TITLE
meta hreflang

### ISSUE THREAD

**Issue by katansky** [zmej-gorunuch/dev.renta#115]
Запіляти ці теги в **<head>** і на всі сторінки також!

`<link rel="alternate" hreflang="uk-UA" href="https://renta.if.ua/ua"/>`
`<link rel="alternate" hreflang="uk" href="https://renta.if.ua/ua"/>`
    
`<link rel="alternate" hreflang="en-UA" href="https://renta.if.ua/en"/>`
`<link rel="alternate" hreflang="en" href="https://renta.if.ua/en"/>`

`<link rel="alternate" hreflang="x-default" href="https://renta.if.ua/ua"/>`

**Comment by zmej-gorunuch** [comment]
готово
