### ISSUE TITLE
Фікс rel=cannonical

### ISSUE THREAD

**Issue by katansky** [zmej-gorunuch/dev.renta#116]
![image](https://user-images.githubusercontent.com/23053495/42307804-557b8256-803c-11e8-9bcf-e591a687f8f5.png)
![image](https://user-images.githubusercontent.com/23053495/42307886-9e5f72de-803c-11e8-82f1-1f7305413e64.png)
на сторінці категорій та оголошень, то відбувається тільки при фільтрації типу: ціні, площі, даті

**Comment by zmej-gorunuch** [comment]
Поправив, має працювати
