### ISSUE TITLE
"Оголошення більше не існує" -  статична сторінка

### ISSUE THREAD

**Issue by katansky** [zmej-gorunuch/dev.renta#119]
Якшо оголошення видалено, можливо потрібно зробити замість 404 редіректу статичну сторінку де буде писати шо тіпа оголошення видалено, більше не існує, шось в цьому роді? Ви шо кажете?

**Comment by klovackdesign** [comment]
Взагалі було б кльово їх не видаляти (ці оголошення), а відправляти в архів (ми з Женьою вже про шось таке говорили раніше). Бо це як не як маса посилань, нам би це було корисно. Але може є якісь але, хз... 

Виглядати це могло б так: слайдер заморожується, стає блідим і зверху такий типу штамп "В архіві" чи щось в цьому роді...

**Comment by katansky** [comment]
думаю потрібно видаляти, до тих пір поки не купимо сервак годний)

**Comment by zmej-gorunuch** [comment]
видаляти і писати, що не актуальне, бо сервак не потягне

**Comment by katansky** [comment]
розібрались!
