### ISSUE TITLE
Площа для земельних ділянок

### ISSUE THREAD

**Issue by klovackdesign** [zmej-gorunuch/dev.renta#125]
Якщо додається ділянка, треба замість м2 давати можливість вказувати площу в сотих.
Може якось при виборі ділянки нехай то поле з площею змінюється, шось таке, хз...

**Comment by zmej-gorunuch** [comment]
думаю що не має потреби, в такому випадку прийдеться всюди таке робити, різні довжини, конвертувати заміри, а толку з того 0 тільки плутанина

**Comment by klovackdesign** [comment]
Ну воно в принципі не критично, це можна вказати в описі, але на майбутнє думає можна врахувати.
