### ISSUE TITLE
"Нагадати пароль" 

### ISSUE THREAD

**Issue by katansky** [zmej-gorunuch/dev.renta#14]
запілити функціонал з нагадування паролю у формі реєстрації.

**Comment by zmej-gorunuch** [comment]
передбач це в верстці або хоч приблизно намалюйте як воно має бути і я додам таку штуку

**Comment by zmej-gorunuch** [comment]
![default](https://user-images.githubusercontent.com/17927037/35388501-c01ac27c-01dc-11e8-9d59-969ee640b43e.png)
