### ISSUE TITLE
Скруглити іконку користувача

### ISSUE THREAD

**Issue by zmej-gorunuch** [zmej-gorunuch/dev.renta#16]
На макеті кругла, а в шаблоні не скруглюється
![default](https://user-images.githubusercontent.com/17927037/35089287-23771828-fc3f-11e7-8db2-41c6021b60b3.png)

**Comment by katansky** [comment]
style.css - в 1781 строку необхідно дописати:
**.connection-body-top img{
    -webkit-border-radius: 50% !important;
    -moz-border-radius: 50% !important;
    border-radius: 50% !important;
}**
