### ISSUE TITLE
Відступ поправити

### ISSUE THREAD

**Issue by zmej-gorunuch** [zmej-gorunuch/dev.renta#18]
Між описом і футером треба збільшити відступ в оголошенні
![default](https://user-images.githubusercontent.com/17927037/35089558-fabf11f0-fc3f-11e7-93b4-f615226a788c.png)

**Comment by katansky** [comment]
в style.css вкінці написати:
**.under-block{
margin-bottom: 40px;
}** 

клас пустий, шукати його не треба.
