### ISSUE TITLE
Переробити пошук оголошень

### ISSUE THREAD

**Issue by zmej-gorunuch** [zmej-gorunuch/dev.renta#19]
Перенести пошук в контроллер оголошень

**Comment by zmej-gorunuch** [comment]
пошуком вже можна користуватись, крім розширеного, в процесі

**Comment by zmej-gorunuch** [comment]
Пошук вже відбувається і по районах міста

**Comment by zmej-gorunuch** [comment]
Пошук працює по ціні і площі
![default](https://user-images.githubusercontent.com/17927037/36946051-9e9e4406-1fbf-11e8-9844-19c3c0b2c1f8.png)

**Comment by klovackdesign** [comment]
Йопта, а чого в тебе всі поля ціни, площі і кількості зиліт в 1?
То в нас така кроссбраузерність крута?

Пошук попробував, вроді гуд шукає.

**Comment by zmej-gorunuch** [comment]
там стилі мінялись і скрипти нові ставили, після того вже так стало)), треба в верстку дивитись, бо на макеті все окремо http://theme.renta.if.ua/filter.html

**Comment by zmej-gorunuch** [comment]
поля поправили, то в мозілі була така проблема

**Comment by zmej-gorunuch** [comment]
додав фільтр по автору, поки що готово
