### ISSUE TITLE
Обмеження назви оголошення по символам

### ISSUE THREAD

**Issue by klovackdesign** [zmej-gorunuch/dev.renta#2]
Треба вирішити, яку максимальну кількість символів може мати назва оголошення.

**Comment by katansky** [comment]
40 максимум!

**Comment by klovackdesign** [comment]
Я б робив макс 50 символів без пробілів.

**Comment by zmej-gorunuch** [comment]
> Я б робив макс 50 символів без пробілів.
пробіл рахується як символ

**Comment by klovackdesign** [comment]
Ну знач так і робимо, макс 50 без пробілів.
