### ISSUE TITLE
Focus в меню

### ISSUE THREAD

**Issue by zmej-gorunuch** [zmej-gorunuch/dev.renta#20]
Я думаю що це баг. Мені така штука не подобається
![default](https://user-images.githubusercontent.com/17927037/35098379-8de49a4c-fc5c-11e7-88c8-f54c5ce0d48e.png)

**Comment by katansky** [comment]
styles.css (513 трока коду)
**.navbar .navbar-nav > li.active > a, .navbar .navbar-nav > li > a:active, .navbar .navbar-nav > li > a:focus, .navbar .navbar-nav > li > a:hover{
**outline: none !important;**
}**
