### ISSUE TITLE
Оголошення 

### ISSUE THREAD

**Issue by zmej-gorunuch** [zmej-gorunuch/dev.renta#23]
Пропоную додати до списку оголошення, щоб зразу можна було перейти до всіх своїх оголошень, бо зараз треба по профілю багато клікати.
![default](https://user-images.githubusercontent.com/17927037/36154571-9481f8f8-10da-11e8-8521-e9eccfce97d7.png)

**Comment by klovackdesign** [comment]
Норм. Мій варіант пунктів у випадайці: 
Профіль
Оголошення
Вихід

Налаштовувати вже собі в профілі будеш...

**Comment by katansky** [comment]
**Питання вирішено - в розробці!**

**Comment by zmej-gorunuch** [comment]
на локалці вже так
![default](https://user-images.githubusercontent.com/17927037/36247393-939175be-123c-11e8-8a44-2c15be78f86b.png)

**Comment by klovackdesign** [comment]
Мені здається шо воно відкривається трохи тупо в лівий бік, давайте зробимо шоб відкривалось в правий....так якось привичніше шолі)

**Comment by zmej-gorunuch** [comment]
зробили в правий
