### ISSUE TITLE
Галерея

### ISSUE THREAD

**Issue by zmej-gorunuch** [zmej-gorunuch/dev.renta#27]
Коли додаєш більше фото блок зіскакує
![default](https://user-images.githubusercontent.com/17927037/36297174-db08b39a-12f9-11e8-9a96-67fc45fa9a57.png)

**Comment by katansky** [comment]
.sidebarWidget.submission { **styles.css (2276)**
    height: auto;
}

**Comment by zmej-gorunuch** [comment]
виправлено
