### ISSUE TITLE
Максимальна к-сть фоток в оголошенні

### ISSUE THREAD

**Issue by klovackdesign** [zmej-gorunuch/dev.renta#3]
Вирішити, яка може бути максимальна кількість фото в оголошенні.

**Comment by katansky** [comment]
7-8 макс!

**Comment by klovackdesign** [comment]
Я б робив 10, не быльше...

**Comment by zmej-gorunuch** [comment]
Поставимо спочатку менше (ресурси не безмежні), а далі буде видно
я за 6 :)

**Comment by klovackdesign** [comment]
Ну якшо так, тоді робимо 5 для початку, а потім вже коли будуть платні пакети, то там вже робити більшу кількість. Так то 5ти фоток мало би бути достатньо думаю, зазнимкувати кухню, тувалєт і ліжко в хаті, чи гараж з штирох боків і середину)

**Comment by zmej-gorunuch** [comment]
я за 5

**Comment by zmej-gorunuch** [comment]
Ставимо 6 і на даний момент питання закриваємо
