### ISSUE TITLE
hr Відступ

### ISSUE THREAD

**Issue by katansky** [zmej-gorunuch/dev.renta#30]
![image](https://user-images.githubusercontent.com/23053495/36684763-0832e628-1b2a-11e8-9b52-bef2aaea0f8f.png)

styles.css, треба добавити (болдом відмітив)
**_2806 строка -_** 
hr.third-line {
    margin-bottom: 15px;
    **overflow: hidden;**
}

**_2812 строка -_** 
hr.fourth-line {
    margin-top: 5px;
    margin-bottom: 10px;
    **overflow: hidden;**
}

**Comment by zmej-gorunuch** [comment]
готово
