### ISSUE TITLE
Search-line width

### ISSUE THREAD

**Issue by katansky** [zmej-gorunuch/dev.renta#31]
![image](https://user-images.githubusercontent.com/23053495/36685152-24da70b0-1b2b-11e8-9d94-8c4ceda4c101.png)

styles.css - 764 строка коду
.form-inline .form-grip{
  **width: 65.2%;**
}

**Comment by zmej-gorunuch** [comment]
![default](https://user-images.githubusercontent.com/17927037/36779163-c44bd01a-1c77-11e8-8191-19dac304600f.png)
**width: 65%;** Так все норм
