### ISSUE TITLE
Пропозиція щодо інформації в блоці з оголошенням

### ISSUE THREAD

**Issue by klovackdesign** [zmej-gorunuch/dev.renta#37]
Пропоную зробити отакі маніпуляції: https://prnt.sc/iovwfv
І можливо подумати подумати над тим щоб розмітити туди ще і телефон...

**Comment by zmej-gorunuch** [comment]
щось я не дуже за те щоб опис виводити, бо там можуть такі коломийки написати, що потім треба буде правити, хоч спробувати можна

**Comment by klovackdesign** [comment]
так оголошення нам ітак на модерацію в подальшому будуть приходити....ну я принаймі так би хотів...а на перших порах да, дивитись за тим виправляти..

треба ще подумати...

**Comment by zmej-gorunuch** [comment]
зробили так
![default](https://user-images.githubusercontent.com/17927037/39192083-105bdb64-47e1-11e8-897e-e8d935abf2f7.png)
