### ISSUE TITLE
Отримання даних з facebook

### ISSUE THREAD

**Issue by zmej-gorunuch** [zmej-gorunuch/dev.renta#39]
Після реєстрації через фейсбук в профіль тягне емейл і стать. Автоматично додає в профіль, якщо дані не заповнені. 
Телефон витягнути не виходить, спробую ще аватарку.

**Comment by klovackdesign** [comment]
Телефон вроді можна кєгнути, коли він публічно відкритий в фб, но єто нє точна))
Аватарку точно можна стягувати... 

А при переавторизації дані будуть ся обновляти? То би було гуд)

**Comment by zmej-gorunuch** [comment]
Маєш на увазі, що при повторній авторизації оновляти дані?
А якщо я захочу, щоб мені листи приходили на іншу пошту, тоді як бути, при авторизації пошту змінить

**Comment by klovackdesign** [comment]
Угу, при повторній авторизації перевіряти дані на фб і оновляти їх. 
На рахунок пошти... Та дати можливість в профілі юзеру її міняти, не?

**Comment by zmej-gorunuch** [comment]
я про таку ситуацію,
на фб пошта vasja@mail, я авторизувався, мені її додало, я змінив в профілі на petja@mail
заходжу на сайт, пошти різні, тягне знову з фб і переписує знову на vasja@mail
я б дуже через таке нервувався))

**Comment by zmej-gorunuch** [comment]
я про таку ситуацію,
на фб пошта vasja@mail, я авторизувався, мені її додало, я змінив в профілі на petja@mail
заходжу на сайт, пошти різні, тягне знову з фб і переписує знову на vasja@mail
я б дуже через таке нервувався))

**Comment by klovackdesign** [comment]
Окей, тоді при авторизації нехай підтягує пошту з фб...а вже на самому сайті дати можливість міняти ту пошту руцями самостійно.. Думаю так буде гуд.

**Comment by zmej-gorunuch** [comment]
ок, так і зроблено

**Comment by zmej-gorunuch** [comment]
Аватарку вже додає також
