### ISSUE TITLE
Прайси

### ISSUE THREAD

**Issue by klovackdesign** [zmej-gorunuch/dev.renta#4]
Придумати і обдумати прайс лист і пакети для клієнтів...

**Comment by zmej-gorunuch** [comment]
для цього завдання треба лейбл (в наступному році)

**Comment by klovackdesign** [comment]
або "Мабуть ніколи" :D

**Comment by katansky** [comment]
Варіанти запропоную до **кінця** місяця, так як є над чим подумати!

**Comment by zmej-gorunuch** [comment]
поки не актуально закоментив
