### ISSUE TITLE
Стилізувати підказки

### ISSUE THREAD

**Issue by zmej-gorunuch** [zmej-gorunuch/dev.renta#41]
![default](https://user-images.githubusercontent.com/17927037/37953955-fc6f637c-31ac-11e8-82db-2315edd717f9.png)
Треба привести до загального виду

**Comment by klovackdesign** [comment]
То де воно таке є?



27 марта 2018, 10:54:13, от "zmej-gorunuch" <notifications@github.com>:


Assigned #41 to @klovackdesign.

**Comment by zmej-gorunuch** [comment]
випливає якщо після виконання дій на сайті, додавання редагування та ін

**Comment by zmej-gorunuch** [comment]
готово 
![default](https://user-images.githubusercontent.com/17927037/39238412-d39bd192-4886-11e8-8738-f6d39502d6c4.png)
