### ISSUE TITLE
Додати до оголошення статус власника

### ISSUE THREAD

**Issue by zmej-gorunuch** [zmej-gorunuch/dev.renta#42]
Пропоную такі статуси
-Власник
-Ріелтор
-Забудовник
-Посередник

**Comment by katansky** [comment]
підтримую, статуси заженем в селект в "ІНФОРМАЦІЯ" оголошення і виведемо цей статус сюди:
![image](https://user-images.githubusercontent.com/23053495/38172622-5911bda0-35b8-11e8-9605-9ed20e5e3d78.png) 
![image](https://user-images.githubusercontent.com/23053495/38172627-63979d6c-35b8-11e8-9d6e-099c77d4218d.png)

**Comment by zmej-gorunuch** [comment]
![default](https://user-images.githubusercontent.com/17927037/38299943-2bb7f678-3804-11e8-994f-cc9983869b3f.png)
