### ISSUE TITLE
Добавити інфу про "договірну ціну"

### ISSUE THREAD

**Issue by katansky** [zmej-gorunuch/dev.renta#47]
![image](https://user-images.githubusercontent.com/23053495/38172978-c1b6b0bc-35be-11e8-91f8-6fa7a758e927.png)

`<h3 class="pull-right">1 337 грн.<br><span>Ціна договірна</span></h3>`

**Comment by zmej-gorunuch** [comment]
в процесі, додаю в базу даних можливість вибору

**Comment by zmej-gorunuch** [comment]
готово є два статуси
- Ціна без торгу
- Ціна договірна

![default](https://user-images.githubusercontent.com/17927037/38190671-f413395e-366d-11e8-8b47-1c13ccf0974e.png)
