### ISSUE TITLE
Сторінки з проблемними шрифтами

### ISSUE THREAD

**Issue by klovackdesign** [zmej-gorunuch/dev.renta#61]
1. https://prnt.sc/jaqxba
2. https://prnt.sc/jaqxm9
3. https://prnt.sc/jaqy1v
4. https://prnt.sc/jaqyhs
5. https://prnt.sc/jar0d8
6. https://prnt.sc/jasht7
7. https://prnt.sc/jcy83x

**Comment by katansky** [comment]
пофіксив
