### ISSUE TITLE
Аватарка для адміна

### ISSUE THREAD

**Issue by zmej-gorunuch** [zmej-gorunuch/dev.renta#65]
Треба аватарку для адміністрації
![default](https://user-images.githubusercontent.com/17927037/39383170-eb18732a-4a70-11e8-81cd-23308f48aeaf.png)

**Comment by klovackdesign** [comment]
![avatar](https://user-images.githubusercontent.com/31410258/39404472-96b41230-4b9c-11e8-9a2f-a9568c682326.png)
![avatar2](https://user-images.githubusercontent.com/31410258/39404473-96db6a88-4b9c-11e8-9376-5cab2b9cf842.png)
