### ISSUE TITLE
Пропозиція щодо "дії" в пошуку

### ISSUE THREAD

**Issue by klovackdesign** [zmej-gorunuch/dev.renta#66]
Пропоную тут https://prnt.sc/jbinrh зробити: Купити і Орендувати (або "В оренду" щоб менше по ширині місця займало)...

**Comment by zmej-gorunuch** [comment]
можна і так, щоб зрозуміліше було
з адмінки заміни

**Comment by klovackdesign** [comment]
Змінив, отака біда тепер:

![image](https://user-images.githubusercontent.com/31410258/39521685-38dda5ee-4e18-11e8-875a-411447fa85df.png)

**Comment by klovackdesign** [comment]
На сторінці з оголошеннями також злетіло

![image](https://user-images.githubusercontent.com/31410258/39521713-578d50c0-4e18-11e8-8120-4bf80740b183.png)

**Comment by klovackdesign** [comment]
і раз ми вже міняємо на "Орендувати", то плашку треба підігнати теж отут:

![image](https://user-images.githubusercontent.com/31410258/39550848-698afb6c-4e6b-11e8-9b87-4f72735e8843.png)

**Comment by zmej-gorunuch** [comment]
ставимо все як було, поки сайт на індексації
