### ISSUE TITLE
Замінити фавікон

### ISSUE THREAD

**Issue by klovackdesign** [zmej-gorunuch/dev.renta#68]
[favicons.zip](https://github.com/zmej-gorunuch/dev.renta/files/1958557/favicons.zip)

**Comment by zmej-gorunuch** [comment]
замінив, перевірте чи робит, бо я не в курсі)))

**Comment by klovackdesign** [comment]
На десктопі робит в мозілі тільки. Опера і хром отака хрєнь:

![image](https://user-images.githubusercontent.com/31410258/39520887-e3237f14-4e14-11e8-8e35-eb72bfd1e9d2.png)

**Comment by zmej-gorunuch** [comment]
перевіряйте тепер

**Comment by klovackdesign** [comment]
в мене ніц не змінилося, усьо як було...
а в фаерфоксі взагалі тепер не відображає його...на деяких сторінках старий відображає...

**Comment by zmej-gorunuch** [comment]
тестовий так і залишився dev.renta.if.ua
але я заливав на основний

**Comment by zmej-gorunuch** [comment]
тепер все має робити
