### ISSUE TITLE
Пропадає + в FAQy

### ISSUE THREAD

**Issue by klovackdesign** [zmej-gorunuch/dev.renta#7]
Після того як відкриваєш/закриваєш питання, пропадає іконка +

![image](https://user-images.githubusercontent.com/31410258/34949057-a26b0286-fa17-11e7-985c-571c2749be53.png)

**Comment by katansky** [comment]
![image](https://user-images.githubusercontent.com/23053495/35047875-09111e5c-fba4-11e7-9895-c8bc9d995eee.png)
прикол в тому, що сайт думає, що та картинка має бути в директорії "/en

**Comment by zmej-gorunuch** [comment]
було все простіше, готово
