### ISSUE TITLE
Зробити автоматичним наповнення sitemap

### ISSUE THREAD

**Issue by katansky** [zmej-gorunuch/dev.renta#78]
Приклад тут - https://bar-data.com/blog/yii2/simple-sitemap-for-site-on-yii2
Бо вручну вводити захаримся, **поки що не чіпати файл sitemap.xml** 
![image](https://user-images.githubusercontent.com/23053495/39672107-8d838a66-512c-11e8-9821-d0888ab4f1ef.png)

**Comment by zmej-gorunuch** [comment]
готово
