### ISSUE TITLE
Політика конфіденційності

### ISSUE THREAD

**Issue by klovackdesign** [zmej-gorunuch/dev.renta#8]
Придумати, що має бути на цій сторінці.... Я чесно кажучи хз, шо переважно на них пишуть, треба буде подивитись)))

**Comment by katansky** [comment]
я зроблю! до **22.01**, скрініть!

**Comment by klovackdesign** [comment]
ебош)

**Comment by katansky** [comment]
політика є на деві, завтра перенесем на мейн!
