### ISSUE TITLE
Назва вилазить на зображення в facebook

### ISSUE THREAD

**Issue by zmej-gorunuch** [zmej-gorunuch/dev.renta#81]
![default](https://user-images.githubusercontent.com/17927037/40060187-ba2ba010-585e-11e8-85c1-ad402065c792.png)
треба ту картинку переробити

**Comment by klovackdesign** [comment]
![image](https://user-images.githubusercontent.com/31410258/40312642-1b2008d6-5d1c-11e8-8755-dabdb5ad9ec4.jpg)

**Comment by zmej-gorunuch** [comment]
змініть ще на сторінці)

**Comment by klovackdesign** [comment]
хз, в мене там прав немає

**Comment by katansky** [comment]
є, змінили!
