### ISSUE TITLE
Підкатегорії і структура сторінок на сайті

### ISSUE THREAD

**Issue by klovackdesign** [zmej-gorunuch/dev.renta#87]
Треба продумати структуру сторінок і підкатегорії на сайті

**Мої пропозиції:**

Продаж нерухомості Івано-Франківськ
- купити квартиру
- купити гараж
- купити будинок
- купити дачу

Оренда нерухомості Івано-Франківськ
- зняти кімнату
- зняти квартиру
- зняти офіс
- зняти будинок

якось так...

**Comment by zmej-gorunuch** [comment]
так нормально, оренда і продаж основні, а всі інші вже як підкатегорії

**Comment by klovackdesign** [comment]
Хз, може ще додумати...треба глянути по запитам. Чи стане для початку?

**Comment by zmej-gorunuch** [comment]
треба добре обдумати, бо там є що робити
