### ISSUE TITLE
Випадайка при кліку на нікнейм юзера

### ISSUE THREAD

**Issue by klovackdesign** [zmej-gorunuch/dev.renta#9]
Зараз випадайка випадає тільки коли клікнеш на іконку, а здалось би щоб іконка і нік були як одне ціле, що при кліку, і на то, і на то випадайка випадала:

![image](https://user-images.githubusercontent.com/31410258/34949483-e3091e58-fa18-11e7-8aa0-213373636a82.png)

**Comment by katansky** [comment]
**Питання вирішено!**
