### ISSUE TITLE
Обрізати в Description символи <p> <span> і т.д

### ISSUE THREAD

**Issue by katansky** [zmej-gorunuch/dev.renta#98]
![image](https://user-images.githubusercontent.com/23053495/40726089-ad73fd74-642d-11e8-95b4-a84be66f2f2d.png)
Воно тяне символи з Редактора!

**Comment by zmej-gorunuch** [comment]
![default](https://user-images.githubusercontent.com/17927037/40851757-0247302e-65d1-11e8-810d-661f875759da.png)
